wget "https://www.basissetexchange.org/api/basis/cc-pvdz/format/gaussian94/?version=0&elements=1" -O 01.gaussian94
wget "https://www.basissetexchange.org/api/basis/cc-pvdz/format/gaussian94/?version=0&elements=2" -O 02.gaussian94
wget "https://www.basissetexchange.org/api/basis/cc-pvdz/format/gaussian94/?version=0&elements=3" -O 03.gaussian94
wget "https://www.basissetexchange.org/api/basis/cc-pvdz/format/gaussian94/?version=0&elements=4" -O 04.gaussian94
wget "https://www.basissetexchange.org/api/basis/cc-pvdz/format/gaussian94/?version=0&elements=5" -O 05.gaussian94
wget "https://www.basissetexchange.org/api/basis/cc-pvdz/format/gaussian94/?version=0&elements=6" -O 06.gaussian94
wget "https://www.basissetexchange.org/api/basis/cc-pvdz/format/gaussian94/?version=0&elements=7" -O 07.gaussian94
wget "https://www.basissetexchange.org/api/basis/cc-pvdz/format/gaussian94/?version=0&elements=8" -O 08.gaussian94
wget "https://www.basissetexchange.org/api/basis/cc-pvdz/format/gaussian94/?version=0&elements=9" -O 09.gaussian94
wget "https://www.basissetexchange.org/api/basis/cc-pvdz/format/gaussian94/?version=0&elements=10" -O 10.gaussian94
wget "https://www.basissetexchange.org/api/basis/cc-pvdz/format/gaussian94/?version=0&elements=11" -O 11.gaussian94
wget "https://www.basissetexchange.org/api/basis/cc-pvdz/format/gaussian94/?version=0&elements=12" -O 12.gaussian94
wget "https://www.basissetexchange.org/api/basis/cc-pvdz/format/gaussian94/?version=0&elements=13" -O 13.gaussian94
wget "https://www.basissetexchange.org/api/basis/cc-pvdz/format/gaussian94/?version=0&elements=14" -O 14.gaussian94
wget "https://www.basissetexchange.org/api/basis/cc-pvdz/format/gaussian94/?version=0&elements=15" -O 15.gaussian94
wget "https://www.basissetexchange.org/api/basis/cc-pvdz/format/gaussian94/?version=0&elements=16" -O 16.gaussian94
wget "https://www.basissetexchange.org/api/basis/cc-pvdz/format/gaussian94/?version=0&elements=17" -O 17.gaussian94
wget "https://www.basissetexchange.org/api/basis/cc-pvdz/format/gaussian94/?version=0&elements=18" -O 18.gaussian94
